#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=37 \
  blur_radius=30 \
  position=top \
  sticky=off \
  padding_left=10 \
  padding_right=10 \
  color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:13.0" \
  icon.color=$WHITE \
  label.font="SF Pro:Semibold:13.0" \
  label.color=$WHITE \
  background.drawing=off \
  padding_left=4 \
  padding_right=4 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=4 \
  icon.padding_right=4

# -- Left Island Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Island Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/right_separator.sh
source $ITEM_DIR/battery.sh

# -- Island Brackets --
source $ITEM_DIR/brackets.sh

##### Finalizing Setup #####
sketchybar --update
